"""empty message

Revision ID: 06f5849ebe0b
Revises: aaaedcf1a5c7
Create Date: 2025-02-14 23:28:11.408194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f5849ebe0b'
down_revision = 'aaaedcf1a5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
     batch_op.add_column(sa.Column('date_issued', sa.Date(), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('date_issued')

    # ### end Alembic commands ###
