"""empty message

Revision ID: 11029f04b9ea
Revises: 3b1885efb225
Create Date: 2025-03-06 18:23:16.761153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11029f04b9ea'
down_revision = '3b1885efb225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.drop_column('manual_number')

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.drop_column('manual_number')

    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.drop_column('manual_number')

    # ### end Alembic commands ###
