"""empty message

Revision ID: 1143ff4cbe79
Revises: 23151009b0aa
Create Date: 2025-01-30 21:48:09.972774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1143ff4cbe79'
down_revision = '23151009b0aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_account', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('account_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('sub_account_details', sa.JSON(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('sub_account_details')
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_name')
        batch_op.drop_column('parent_account')

    # ### end Alembic commands ###
