"""empty message

Revision ID: 19499814ff8f
Revises: d2b9f519d506
Create Date: 2025-02-07 22:57:18.859083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '19499814ff8f'
down_revision = 'd2b9f519d506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.drop_column('sub_accounts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_accounts', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
