from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1fba3eae4fc2'
down_revision = '5049af569054'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('account_credited',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('grn_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

        # Only drop the column without touching the constraint
        batch_op.drop_column('coa_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        # Add the column back
        batch_op.add_column(sa.Column('coa_id', sa.INTEGER(), nullable=True))
        
        # Recreate the foreign key constraint (use the correct name here)
        batch_op.create_foreign_key('chart_of_accounts', 'chart_of_accounts', ['coa_id'], ['id'])
        
        # Reverse column alterations
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('grn_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('account_credited',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
