"""empty message

Revision ID: 2849fd8bd28f
Revises: 1143ff4cbe79
Create Date: 2025-01-31 15:21:04.165164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2849fd8bd28f'
down_revision = '1143ff4cbe79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_received',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coa_id', sa.Integer(), nullable=True),
    sa.Column('account_debited', sa.String(length=100), nullable=True),
    sa.Column('account_credited', sa.String(length=100), nullable=True),
    sa.Column('grn_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['coa_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'invoice_number', name='unique_invoice_per_user')
    )
    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.drop_column('sub_accounts')
        batch_op.drop_column('parent_account')
        batch_op.drop_column('account_class')

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.drop_column('parent_account')
        batch_op.drop_column('account_class')
        batch_op.drop_column('account_type')

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.drop_column('grn_number')
        batch_op.drop_column('parent_account')
        batch_op.drop_column('invoice_type')
        batch_op.drop_column('sub_accounts')
        batch_op.drop_column('account_class')
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('account_class', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('sub_accounts', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('invoice_type', sa.VARCHAR(length=100), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('parent_account', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('grn_number', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('account_class', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('parent_account', sa.VARCHAR(length=150), nullable=False))

    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_class', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('parent_account', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('sub_accounts', sqlite.JSON(), nullable=True))

    op.drop_table('invoice_received')
    # ### end Alembic commands ###
