"""empty message

Revision ID: 2edf2ee23947
Revises: dd50ebeb5756
Create Date: 2025-03-03 16:00:48.885858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edf2ee23947'
down_revision = 'dd50ebeb5756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_debited', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.drop_column('account_debited')

    # ### end Alembic commands ###
