"""Added user relationship to InvoiceReceived

Revision ID: 366a54d5aac3
Revises: 
Create Date: 2025-03-04 01:42:46.805146
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366a54d5aac3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))  # Temporarily nullable
        batch_op.create_foreign_key('fk_cash_receipt_journal_created_by', 'user', ['created_by'], ['id'])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cash_receipt_journal_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')
