"""empty message

Revision ID: 3b1885efb225
Revises: 17bc284153f8
Create Date: 2025-03-04 10:49:19.633399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1885efb225'
down_revision = '17bc284153f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.alter_column('bank',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint('unique_receipt_per_user', ['created_by', 'receipt_no'])

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residence', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('member_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('church_name', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('unique_member_number', ['member_number'])  # Corrected the name here

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_member_number', type_='unique')  # Corrected the name here
        batch_op.drop_column('church_name')
        batch_op.drop_column('member_number')
        batch_op.drop_column('occupation')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('residence')

    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.drop_constraint('unique_receipt_per_user', type_='unique')
        batch_op.alter_column('bank',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
