"""empty message

Revision ID: 4485e2840e2d
Revises: b3e871dcea37
Create Date: 2025-06-14 18:21:47.809470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4485e2840e2d'
down_revision = 'b3e871dcea37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_reconciliation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_date', sa.Date(), nullable=False),
    sa.Column('bank_account', sa.String(length=100), nullable=False),
    sa.Column('statement_balance', sa.Float(), nullable=False),
    sa.Column('reconciled_balance', sa.Float(), nullable=False),
    sa.Column('adjusted_balance', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_reconciliation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('cleared', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['bank_reconciliation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_reconciliation_item')
    op.drop_table('bank_reconciliation')
    # ### end Alembic commands ###
