"""empty message

Revision ID: 58a6904b8bc1
Revises: f12943dc6bd9
Create Date: 2025-02-03 18:22:16.708199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a6904b8bc1'
down_revision = 'f12943dc6bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
