"""empty message

Revision ID: 65c9fc416a5d
Revises: a900af57aa73
Create Date: 2025-02-05 22:26:09.999215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c9fc416a5d'
down_revision = 'a900af57aa73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    with op.batch_alter_table('payee', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
