"""empty message

Revision ID: 6882ceb7f03c
Revises: 65c9fc416a5d
Create Date: 2025-02-05 23:30:29.269969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6882ceb7f03c'
down_revision = '65c9fc416a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.drop_column('receipt_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_type', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
