"""empty message

Revision ID: 69be96da3c94
Revises: 6882ceb7f03c
Create Date: 2025-02-05 23:34:04.031831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69be96da3c94'
down_revision = '6882ceb7f03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.drop_column('receipt_type')

    # ### end Alembic commands ###
