"""empty message

Revision ID: 6e68c3bd6fd9
Revises: 20d8dfa59075
Create Date: 2025-03-16 19:49:33.074885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e68c3bd6fd9'
down_revision = '20d8dfa59075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate', schema=None) as batch_op:
        batch_op.alter_column('procurement_method',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate', schema=None) as batch_op:
        batch_op.alter_column('procurement_method',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
