"""empty message

Revision ID: 85d6fa21a393
Revises: d23e09889179
Create Date: 2025-02-02 22:21:26.216000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d6fa21a393'
down_revision = 'd23e09889179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credited_account_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('debited_account_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('debited_account_name')
        batch_op.drop_column('credited_account_name')

    # ### end Alembic commands ###
