"""empty message

Revision ID: 8a810b726b33
Revises: 2243078ca9df
Create Date: 2025-01-07 20:19:55.881523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a810b726b33'
down_revision = '2243078ca9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
