"""empty message

Revision ID: 975c3a79cb3a
Revises: 6e68c3bd6fd9
Create Date: 2025-03-16 20:48:47.192156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975c3a79cb3a'
down_revision = '6e68c3bd6fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_expenditure', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate', schema=None) as batch_op:
        batch_op.drop_column('actual_expenditure')

    # ### end Alembic commands ###
