"""Added user relationship to InvoiceReceived

Revision ID: 9ddeb70ffb58
Revises: 1fba3eae4fc2
Create Date: 2025-03-03 15:56:29.163748
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9ddeb70ffb58'
down_revision = '1fba3eae4fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coa_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('account_debited',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('account_credited',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('grn_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

        # Add a foreign key constraint with a name
        batch_op.create_foreign_key('fk_invoice_received_coa_id', 'chart_of_accounts', ['coa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        # Drop the foreign key constraint by its name
        batch_op.drop_constraint('fk_invoice_received_coa_id', type_='foreignkey')

        batch_op.alter_column('grn_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('account_credited',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('account_debited',
               existing_type=sa.String(length=100),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('coa_id')

    # ### end Alembic commands ###
