"""empty message

Revision ID: a900af57aa73
Revises: 58a6904b8bc1
Create Date: 2025-02-05 22:24:27.600746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a900af57aa73'
down_revision = '58a6904b8bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payee', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
