"""empty message

Revision ID: aaaedcf1a5c7
Revises: 
Create Date: 2025-02-13 20:51:01.619454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaaedcf1a5c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.drop_column('account_credited_id')
        batch_op.drop_column('account_credited_type')
        batch_op.drop_column('account_debited_type')
        batch_op.drop_column('account_debited_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_debited_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('account_debited_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('account_credited_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('account_credited_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
