"""empty message

Revision ID: ab8613cbf444
Revises: 366a54d5aac3
Create Date: 2025-03-04 01:51:43.481273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8613cbf444'
down_revision = '366a54d5aac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('church_name')
        batch_op.drop_column('occupation')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('member_number')
        batch_op.drop_column('residence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residence', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('member_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('church_name', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
