"""empty message

Revision ID: b16e501b9c4f
Revises: 11029f04b9ea
Create Date: 2025-03-06 19:23:03.197342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16e501b9c4f'
down_revision = '11029f04b9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.alter_column('manual_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.alter_column('manual_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.alter_column('manual_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.alter_column('manual_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.alter_column('manual_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.alter_column('manual_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
