"""empty message

Revision ID: b74540d3976a
Revises: 2535485d5f83
Create Date: 2025-06-14 21:05:14.225426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74540d3976a'
down_revision = '2535485d5f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashbook_reconciliation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('bank_account', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('transaction_details', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('manual_number', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bank_reconciliation_item')
    op.drop_table('bank_reconciliation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_reconciliation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reconciliation_date', sa.DATE(), nullable=False),
    sa.Column('bank_account', sa.VARCHAR(length=100), nullable=False),
    sa.Column('statement_balance', sa.FLOAT(), nullable=False),
    sa.Column('reconciled_balance', sa.FLOAT(), nullable=False),
    sa.Column('adjusted_balance', sa.FLOAT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_reconciliation_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reconciliation_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_date', sa.DATE(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('cleared', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cleared_date', sa.DATE(), nullable=True),
    sa.Column('is_reconciled', sa.BOOLEAN(), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('counterparty', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['bank_reconciliation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cashbook_reconciliation')
    # ### end Alembic commands ###
