"""empty message

Revision ID: c5c17d6b07e2
Revises: 
Create Date: 2025-02-25 19:23:41.219104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c17d6b07e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('parent_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_parent_account_id', 'chart_of_accounts', ['parent_account_id'], ['id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('date_issued',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('date_issued',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chart_of_accounts_parent', type_='foreignkey')  # Use the constraint name
        batch_op.drop_column('parent_account_id')
        batch_op.drop_column('note_number')

    # ### end Alembic commands ###
