"""empty message

Revision ID: d2b9f519d506
Revises: 2bc28d7802db
Create Date: 2025-02-06 09:52:20.510889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b9f519d506'
down_revision = '2bc28d7802db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.alter_column('from_whom_received',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('cashbook',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipt_journal', schema=None) as batch_op:
        batch_op.alter_column('cashbook',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('from_whom_received',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
