"""empty message

Revision ID: dd50ebeb5756
Revises: 9ddeb70ffb58
Create Date: 2025-03-03 15:59:06.529290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd50ebeb5756'
down_revision = '9ddeb70ffb58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.drop_column('account_debited')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_debited', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
