"""empty message

Revision ID: f12943dc6bd9
Revises: f61d402e6814
Create Date: 2025-02-03 12:07:32.318904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12943dc6bd9'
down_revision = 'f61d402e6814'
branch_labels = None
depends_on = None
def upgrade():
    with op.batch_alter_table('invoice_issued') as batch_op:
        # Remove the problematic constraint drop, since it doesn't exist
        batch_op.drop_column('coa_id')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_issued', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'chart_of_accounts', ['coa_id'], ['id'])

    # ### end Alembic commands ###
