"""empty message

Revision ID: f37ad1ad0f52
Revises: eb1b7a697415
Create Date: 2025-03-11 19:09:05.748742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37ad1ad0f52'
down_revision = 'eb1b7a697415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.alter_column('cashbook',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_disbursement_journal', schema=None) as batch_op:
        batch_op.alter_column('cashbook',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
